"""empty message

Revision ID: f45a44fd3965
Revises: 834b1a697901
Create Date: 2023-02-24 22:13:01.704119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f45a44fd3965'
down_revision = '834b1a697901'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('likes', sa.Integer(), nullable=True))
    op.add_column('post', sa.Column('dislikes', sa.Integer(), nullable=True))
    op.add_column('post', sa.Column('laughs', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'laughs')
    op.drop_column('post', 'dislikes')
    op.drop_column('post', 'likes')
    # ### end Alembic commands ###
